'use client'

import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add('visible')
        })
      },
      { threshold: 0.1, rootMargin: '0px 0px -60px 0px' }
    )
    document.querySelectorAll('.reveal').forEach((el) => observer.observe(el))
    return () => observer.disconnect()
  }, [])

  const experiences = [
    { icon: '☕', name: 'Espresso Ritual', sub: 'The Foundation' },
    { icon: '🧊', name: 'Cold & Bold', sub: 'Iced Perfection' },
    { icon: '✦', name: 'Signature Lattes', sub: 'Our Creations' },
    { icon: '🥐', name: 'Pastries & Pairings', sub: 'The Complement' },
    { icon: '◉', name: 'Whole Bean', sub: 'Take It Home' },
    { icon: '◈', name: 'Office Coffee', sub: 'For Teams' },
  ]
  const products = [
    { label: 'Signature', name: 'Morning Essentials', desc: 'Espresso, cortado, americano — the core ritual.', bg: "url('/images/espresso-glass.png') center/cover" },
    { label: 'Premium', name: 'Signature Espresso', desc: 'Single-origin, handcrafted, atmospheric.', bg: "url('/images/matte-cup.png') center/cover" },
    { label: 'Iced', name: 'Cold & Bold', desc: 'Cold brew, iced latte, nitro — city pace energy.', bg: "url('/images/iced-splash.png') center/cover" },
    { label: 'Seasonal', name: 'Seasonal Rituals', desc: 'Limited collections that change with the moment.', bg: "url('/images/scifi-latte.png') center/cover" },
    { label: 'Pastry', name: 'Pastries & Pairings', desc: 'The perfect complement to every cup.', bg: "url('/images/coffee-trio.png') center/cover" },
    { label: 'Retail', name: 'Take-Home Beans', desc: 'Bring the ritual home. Whole bean. Ground. Capsules.', bg: "url('/images/espresso-shot.jpg') center/cover" },
  ]
  const clubPerks = [
    { title: 'Seasonal Previews', desc: 'First access to limited drops and new blends.' },
    { title: 'Loyalty Rewards', desc: 'Points on every purchase. Redeemable for menu items.' },
    { title: 'Birthday Perks', desc: 'A complimentary drink on your day. Every year.' },
    { title: 'Member Drops', desc: 'Exclusive merch and retail offers.' },
  ]

  return (
    <>
      <style jsx global>{`
        :root{--espresso:#2C1810;--espresso-deep:#1A0E08;--black:#0E0E0E;--bronze:#B8860B;--bronze-light:#D4A54A;--cream:#F5F0E8;--taupe:#8B7D6B;--wood:#5C4A3A;--font-display:'Cormorant Garamond',Georgia,serif;--font-body:'DM Sans',system-ui,sans-serif;--ease-expo:cubic-bezier(0.16,1,0.3,1);--ease-smooth:cubic-bezier(0.37,0,0.63,1);--text-hero:clamp(52px,10vw,150px);--text-section:clamp(32px,5vw,68px);--text-body-lg:clamp(14px,1.3vw,18px);--text-caption:clamp(9px,0.85vw,11px)}*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth}body{background:var(--black);color:var(--cream);font-family:var(--font-body);font-weight:300;overflow-x:hidden;-webkit-font-smoothing:antialiased}body::after{content:'';position:fixed;inset:0;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.035'/%3E%3C/svg%3E");pointer-events:none;z-index:9999}
        .hero-video{position:absolute;inset:0;z-index:0;overflow:hidden}.hero-video video{width:100%;height:100%;object-fit:cover;opacity:0.55}
        nav{position:fixed;top:0;left:0;right:0;z-index:100;padding:28px 56px;display:flex;justify-content:space-between;align-items:center;mix-blend-mode:difference}.nav-logo{font-family:var(--font-display);font-size:22px;font-weight:500;letter-spacing:.08em;color:var(--cream)}.nav-logo span{font-weight:300;font-style:italic;opacity:.7}.nav-links{display:flex;gap:36px;list-style:none}.nav-links a{color:var(--cream);text-decoration:none;font-size:11px;letter-spacing:.25em;text-transform:uppercase;font-weight:400;opacity:.6;transition:opacity .3s}.nav-links a:hover{opacity:1}
        .hero{position:relative;height:100vh;min-height:700px;display:flex;align-items:flex-end;padding:0 56px 100px;overflow:hidden}.hero-bg{position:absolute;inset:0;z-index:1;background:linear-gradient(180deg,rgba(14,14,14,0.25) 0%,rgba(14,14,14,0.55) 40%,rgba(14,14,14,0.93) 100%)}.hero-light{position:absolute;top:0;right:20%;width:400px;height:100%;background:linear-gradient(180deg,rgba(245,240,232,.06) 0%,rgba(184,134,11,.04) 30%,transparent 70%);transform:rotate(-5deg) skewX(-5deg);filter:blur(60px);animation:morningLight 8s var(--ease-smooth) infinite}@keyframes morningLight{0%,100%{opacity:.5}50%{opacity:1}}.steam{position:absolute;bottom:30%;width:80px;height:200px;background:radial-gradient(ellipse,rgba(245,240,232,.04) 0%,transparent 70%);filter:blur(20px);animation:steamRise 6s var(--ease-smooth) infinite}@keyframes steamRise{0%{transform:translateY(0) scaleX(1);opacity:0}20%{opacity:.4}80%{opacity:0}100%{transform:translateY(-150px) scaleX(1.5);opacity:0}}
        .hero-content{position:relative;z-index:2;max-width:800px}.hero-tag{font-size:var(--text-caption);letter-spacing:.5em;text-transform:uppercase;color:var(--bronze);margin-bottom:28px;opacity:0;transform:translateY(30px);animation:revealUp .8s var(--ease-expo) .4s forwards}.hero h1{font-family:var(--font-display);font-size:var(--text-hero);font-weight:300;line-height:.95;letter-spacing:-.01em;margin-bottom:36px;opacity:0;transform:translateY(60px);animation:revealUp 1s var(--ease-expo) .6s forwards}.hero h1 em{font-style:italic;font-weight:500;color:var(--bronze-light)}.hero-sub{font-size:var(--text-body-lg);font-weight:300;line-height:1.8;max-width:480px;color:rgba(245,240,232,.5);margin-bottom:52px;opacity:0;transform:translateY(40px);animation:revealUp .8s var(--ease-expo) .9s forwards}.hero-ctas{display:flex;gap:16px;flex-wrap:wrap;opacity:0;transform:translateY(30px);animation:revealUp .8s var(--ease-expo) 1.1s forwards}@keyframes revealUp{to{opacity:1;transform:translateY(0)}}
        .btn-warm{display:inline-flex;align-items:center;gap:10px;padding:16px 44px;background:var(--bronze);color:var(--black);font-family:var(--font-body);font-size:11px;font-weight:600;letter-spacing:.2em;text-transform:uppercase;text-decoration:none;border:none;cursor:pointer;transition:all .5s var(--ease-expo);position:relative;overflow:hidden}.btn-warm::before{content:'';position:absolute;inset:0;background:var(--bronze-light);transform:translateX(-100%);transition:transform .5s var(--ease-expo)}.btn-warm:hover::before{transform:translateX(0)}.btn-warm span{position:relative;z-index:1}.btn-outline{display:inline-flex;align-items:center;gap:10px;padding:16px 44px;background:transparent;color:var(--cream);font-family:var(--font-body);font-size:11px;font-weight:400;letter-spacing:.2em;text-transform:uppercase;text-decoration:none;border:1px solid rgba(245,240,232,.15);cursor:pointer;transition:all .4s var(--ease-expo)}.btn-outline:hover{border-color:var(--bronze);color:var(--bronze-light)}
        .experience{padding:100px 56px;border-top:1px solid rgba(184,134,11,.08)}.exp-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;background:rgba(184,134,11,.06);margin-top:48px}.exp-tile{background:var(--black);padding:40px 24px;text-align:center;cursor:pointer;transition:all .5s var(--ease-expo);position:relative}.exp-tile::after{content:'';position:absolute;bottom:0;left:50%;right:50%;height:1px;background:var(--bronze);transition:all .5s var(--ease-expo)}.exp-tile:hover{background:rgba(184,134,11,.03)}.exp-tile:hover::after{left:20%;right:20%}.exp-tile-icon{font-size:28px;margin-bottom:16px;opacity:.6;transition:opacity .3s}.exp-tile:hover .exp-tile-icon{opacity:1}.exp-tile-name{font-family:var(--font-display);font-size:16px;font-weight:500;letter-spacing:.05em;margin-bottom:6px}.exp-tile-sub{font-size:10px;color:var(--taupe);letter-spacing:.15em;text-transform:uppercase}
        .story{padding:160px 56px;display:grid;grid-template-columns:1.2fr 1fr;gap:100px;align-items:center}.story-headline{font-family:var(--font-display);font-size:clamp(36px,5.5vw,72px);font-weight:300;line-height:1.1}.story-headline em{font-style:italic;font-weight:500;display:block;color:var(--bronze-light)}.story-line{width:48px;height:1px;background:var(--bronze);margin:32px 0}.story-right p{font-size:var(--text-body-lg);line-height:1.9;color:rgba(245,240,232,.5);margin-bottom:20px}
        .products{padding:120px 56px}.products-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;margin-top:48px}.product-card{position:relative;aspect-ratio:3/4;overflow:hidden;cursor:pointer;background:var(--espresso-deep)}.product-card-bg{position:absolute;inset:0;transition:transform 1.2s var(--ease-expo)}.product-card:hover .product-card-bg{transform:scale(1.06)}.product-card-overlay{position:absolute;inset:0;background:linear-gradient(180deg,transparent 50%,rgba(14,14,14,.85) 100%)}.product-card-content{position:absolute;bottom:0;left:0;right:0;padding:36px}.product-card-label{font-size:9px;letter-spacing:.4em;text-transform:uppercase;color:var(--bronze);margin-bottom:8px}.product-card-name{font-family:var(--font-display);font-size:24px;font-weight:500;letter-spacing:.03em;margin-bottom:8px}.product-card-desc{font-size:12px;color:rgba(245,240,232,.4);line-height:1.6}
        .life{padding:120px 56px}.life-scenes{display:grid;grid-template-columns:2fr 1fr;grid-template-rows:350px 350px;gap:2px;margin-top:48px}.life-scene{position:relative;overflow:hidden}.life-scene:first-child{grid-row:1/3}.life-scene-bg{position:absolute;inset:0;transition:transform 1.2s var(--ease-expo)}.life-scene:hover .life-scene-bg{transform:scale(1.04)}.life-scene-overlay{position:absolute;inset:0;background:linear-gradient(180deg,transparent 40%,rgba(14,14,14,.6) 100%)}.life-scene-text{position:absolute;bottom:28px;left:28px;font-family:var(--font-display);font-size:16px;font-weight:400;font-style:italic;color:rgba(245,240,232,.6)}
        .retail{padding:120px 56px;text-align:center;border-top:1px solid rgba(184,134,11,.06)}.retail-body{font-size:var(--text-body-lg);color:rgba(245,240,232,.45);max-width:500px;margin:0 auto 48px;line-height:1.8}.retail-items{display:flex;justify-content:center;gap:48px;margin-bottom:48px;flex-wrap:wrap}.retail-item{text-align:center}.retail-item-icon{width:64px;height:64px;border:1px solid rgba(184,134,11,.15);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 12px;font-size:24px;transition:all .4s var(--ease-expo)}.retail-item:hover .retail-item-icon{border-color:var(--bronze);background:rgba(184,134,11,.06)}.retail-item-name{font-family:var(--font-display);font-size:14px;font-weight:500}
        .office{padding:160px 56px;display:grid;grid-template-columns:1fr 1fr;gap:80px;align-items:center;position:relative}.office::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse 50% 50% at 70% 50%,rgba(44,24,16,.3) 0%,transparent 70%)}.office-title{font-family:var(--font-display);font-size:var(--text-section);font-weight:300;line-height:1.1;margin-bottom:24px;position:relative}.office-body{font-size:var(--text-body-lg);color:rgba(245,240,232,.5);line-height:1.8;margin-bottom:40px;position:relative}
        .club{padding:120px 56px;border-top:1px solid rgba(184,134,11,.06);display:grid;grid-template-columns:1fr 1fr;gap:80px;align-items:center}.club-perks{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:32px}.club-perk{padding:24px;border:1px solid rgba(184,134,11,.08);background:rgba(184,134,11,.02);transition:border-color .4s}.club-perk:hover{border-color:rgba(184,134,11,.2)}.club-perk-title{font-family:var(--font-display);font-size:15px;font-weight:600;color:var(--bronze-light);margin-bottom:6px}.club-perk-desc{font-size:12px;color:rgba(245,240,232,.35);line-height:1.6}.club-input{padding:16px 24px;background:rgba(255,255,255,.02);border:1px solid rgba(245,240,232,.08);color:var(--cream);font-family:var(--font-body);font-size:14px;outline:none;transition:border-color .3s;width:100%}.club-input:focus{border-color:var(--bronze)}.club-input::placeholder{color:rgba(245,240,232,.2)}
        .section-label{font-size:var(--text-caption);letter-spacing:.5em;text-transform:uppercase;color:var(--bronze);margin-bottom:16px}.section-title{font-family:var(--font-display);font-size:var(--text-section);font-weight:300;line-height:1.1;margin-bottom:48px;max-width:600px}
        footer{padding:80px 56px 40px;border-top:1px solid rgba(245,240,232,.04);display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:48px}.footer-brand{font-family:var(--font-display);font-size:28px;font-weight:400;letter-spacing:.04em;margin-bottom:16px}.footer-brand span{font-style:italic;font-weight:300;opacity:.6}.footer-tagline{font-size:13px;color:rgba(245,240,232,.25);font-style:italic;line-height:1.6}.footer-col-title{font-size:10px;letter-spacing:.4em;text-transform:uppercase;color:var(--bronze);margin-bottom:20px}.footer-col a{display:block;color:rgba(245,240,232,.35);text-decoration:none;font-size:13px;margin-bottom:12px;transition:color .3s}.footer-col a:hover{color:var(--cream)}.footer-bottom{padding:32px 56px;display:flex;justify-content:space-between;align-items:center;border-top:1px solid rgba(245,240,232,.03);font-size:11px;color:rgba(245,240,232,.15)}.footer-bottom a{color:rgba(245,240,232,.15);text-decoration:none}
        .reveal{opacity:0;transform:translateY(50px);transition:opacity .8s var(--ease-expo),transform .8s var(--ease-expo)}.reveal.visible{opacity:1;transform:translateY(0)}.reveal-d1{transition-delay:.1s}.reveal-d2{transition-delay:.2s}.reveal-d3{transition-delay:.3s}.reveal-d4{transition-delay:.4s}.reveal-d5{transition-delay:.5s}
        @media(max-width:768px){nav{padding:16px 24px}.nav-links{display:none}.hero{padding:0 24px 60px}.exp-grid{grid-template-columns:repeat(3,1fr)}.story{grid-template-columns:1fr;padding:80px 24px;gap:40px}.products{padding:80px 24px}.products-grid{grid-template-columns:1fr 1fr}.life{padding:80px 24px}.life-scenes{grid-template-columns:1fr 1fr;grid-template-rows:auto}.life-scene:first-child{grid-row:auto}.life-scene{min-height:200px}.retail{padding:80px 24px}.office{grid-template-columns:1fr;padding:80px 24px;gap:40px}.club{grid-template-columns:1fr;padding:80px 24px;gap:40px}footer{grid-template-columns:1fr 1fr;padding:60px 24px 30px}.footer-bottom{padding:24px;flex-direction:column;gap:12px}}@media(max-width:480px){.exp-grid{grid-template-columns:repeat(2,1fr)}.products-grid{grid-template-columns:1fr}}
      `}</style>
      <nav><div className="nav-logo">Espresso <span>Co.</span></div><ul className="nav-links"><li><a href="#menu">Menu</a></li><li><a href="#locations">Locations</a></li><li><a href="#beans">Beans & Retail</a></li><li><a href="#club">Coffee Club</a></li><li><a href="#" className="btn-warm" style={{padding:'10px 28px',fontSize:'10px',letterSpacing:'0.15em'}}><span>Order Ahead</span></a></li></ul></nav>
      <section className="hero"><div className="hero-bg"/><div className="hero-video"><video autoPlay muted loop playsInline><source src="/videos/hero.mp4" type="video/mp4"/></video></div><div className="hero-light"/><div className="steam" style={{left:'60%',animationDelay:'0s'}}/><div className="steam" style={{left:'55%',animationDelay:'2s',opacity:0.6}}/><div className="steam" style={{left:'65%',animationDelay:'4s',opacity:0.4}}/><div className="hero-content"><div className="hero-tag">Espresso · Atmosphere · Refined Energy</div><h1>Brewed for<br/>the <em>pace</em><br/>of the city.</h1><p className="hero-sub">Espresso, atmosphere, and refined energy for mornings, meetings, and moments in between.</p><div className="hero-ctas"><a href="#" className="btn-warm"><span>Order Ahead</span></a><a href="#menu" className="btn-outline">View Menu</a><a href="#locations" className="btn-outline">Find a Café</a></div></div></section>
      <section className="experience" id="menu"><div className="section-label reveal">The Experience</div><h2 className="section-title reveal reveal-d1">Every pour, intentional.</h2><div className="exp-grid">{experiences.map((e,i)=>(<div key={i} className={`exp-tile reveal reveal-d${Math.min(i+1,5)}`}><div className="exp-tile-icon">{e.icon}</div><div className="exp-tile-name">{e.name}</div><div className="exp-tile-sub">{e.sub}</div></div>))}</div></section>
      <section className="story"><div className="reveal"><div className="story-headline">For the people who build<em>before noon.</em></div><div className="story-line"/></div><div><p className="reveal reveal-d1">Espresso Co. is designed for people who move with intention. Morning thinkers. Fast starters. Creative builders. Quiet meetings. Daily rituals.</p><p className="reveal reveal-d2">Every pour, every surface, every detail is shaped to make coffee feel like part of a refined way of living.</p><p className="reveal reveal-d3" style={{fontFamily:'var(--font-display)',fontStyle:'italic',color:'var(--bronze-light)',fontSize:'18px'}}>Ritual meets refinement.</p></div></section>
      <section className="products"><div className="section-label reveal">The Menu</div><h2 className="section-title reveal reveal-d1">Crafted categories.</h2><div className="products-grid">{products.map((p,i)=>(<div key={i} className={`product-card reveal reveal-d${Math.min(i+1,4)}`}><div className="product-card-bg" style={{background:p.bg}}/><div className="product-card-overlay"/><div className="product-card-content"><div className="product-card-label">{p.label}</div><div className="product-card-name">{p.name}</div><div className="product-card-desc">{p.desc}</div></div></div>))}</div></section>
      <section className="life"><div className="section-label reveal">The Space</div><h2 className="section-title reveal reveal-d1">Built for quiet ambition.</h2><div className="life-scenes">{[{text:'Built for the morning pace.',bg:"url('/images/cups-on-wood.jpg') center/cover"},{text:'Built for quiet ambition.',bg:"url('/images/matte-cup.png') center/cover"},{text:'Built for the daily ritual.',bg:"url('/images/espresso-glass.png') center/cover"}].map((s,i)=>(<div key={i} className={`life-scene reveal reveal-d${i+1}`}><div className="life-scene-bg" style={{background:s.bg}}/><div className="life-scene-overlay"/><div className="life-scene-text">{s.text}</div></div>))}</div></section>
      <section className="retail" id="beans"><div className="section-label reveal">Retail</div><h2 className="section-title reveal reveal-d1" style={{maxWidth:'none'}}>Bring the ritual home.</h2><p className="retail-body reveal reveal-d2">From whole bean bags to branded tumblers and gift boxes — the Espresso Co. experience extends beyond the café.</p><div className="retail-items reveal reveal-d3">{[{icon:'◉',name:'Bean Bags'},{icon:'◈',name:'Bottled Coffee'},{icon:'◇',name:'Mugs & Tumblers'},{icon:'◆',name:'Gift Boxes'},{icon:'◎',name:'Subscriptions'}].map((r,i)=>(<div key={i} className="retail-item"><div className="retail-item-icon">{r.icon}</div><div className="retail-item-name">{r.name}</div></div>))}</div><a href="#" className="btn-warm reveal reveal-d4"><span>Shop Now</span></a></section>
      <section className="office"><div><div className="section-label reveal">For Teams</div><h2 className="office-title reveal reveal-d1">Coffee service for teams, sets, and elevated events.</h2><p className="office-body reveal reveal-d2">From office subscriptions to event catering and wholesale partnerships — Espresso Co. brings refined coffee service wherever your team builds.</p><a href="#" className="btn-warm reveal reveal-d3"><span>Request Coffee Service</span></a></div><div className="reveal reveal-d2" style={{position:'relative'}}><div style={{aspectRatio:'4/5',background:"linear-gradient(180deg,rgba(14,14,14,0.3) 0%,rgba(14,14,14,0.7) 100%),url('/images/espresso-machine.jpg') center/cover",border:'1px solid rgba(184,134,11,.06)',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{textAlign:'center'}}><div style={{fontFamily:'var(--font-display)',fontSize:'48px',fontWeight:300,color:'var(--bronze-light)',marginBottom:'8px'}}>EC</div><div style={{fontSize:'10px',letterSpacing:'0.3em',textTransform:'uppercase' as const,color:'var(--taupe)'}}>Office Service</div></div></div></div></section>
      <section className="club" id="club"><div><div className="section-label reveal">Membership</div><h2 className="section-title reveal reveal-d1">Join the Coffee Club.</h2><div className="club-perks">{clubPerks.map((p,i)=>(<div key={i} className={`club-perk reveal reveal-d${i+2}`}><div className="club-perk-title">{p.title}</div><div className="club-perk-desc">{p.desc}</div></div>))}</div></div><div style={{display:'flex',flexDirection:'column',gap:'14px'}} className="reveal reveal-d2"><input className="club-input" type="text" placeholder="Full name"/><input className="club-input" type="email" placeholder="Email address"/><input className="club-input" type="tel" placeholder="Phone (for SMS)"/><a href="#" className="btn-warm" style={{textAlign:'center',justifyContent:'center'}}><span>Join the Club</span></a></div></section>
      <footer><div><div className="footer-brand">Espresso <span>Co.</span></div><p className="footer-tagline">Brewed for the Pace of the City.<br/>A Casper Group brand.</p></div><div className="footer-col"><div className="footer-col-title">Order</div><a href="#">Menu</a><a href="#">Order Ahead</a><a href="#">Catering</a><a href="#">Office Coffee</a></div><div className="footer-col"><div className="footer-col-title">Discover</div><a href="#">Locations</a><a href="#">Coffee Club</a><a href="#">Beans & Retail</a><a href="#">About</a></div><div className="footer-col"><div className="footer-col-title">Connect</div><a href="#">Instagram</a><a href="#">TikTok</a><a href="#">Wholesale</a><a href="#">Partnership</a></div></footer>
      <div className="footer-bottom"><span>© 2026 Espresso Co. All rights reserved.</span><span style={{fontSize:'10px',letterSpacing:'0.2em',textTransform:'uppercase' as const}}>A <a href="#">Casper Group</a> Brand</span></div>
    </>
  )
}
